import { IUserInfo } from "@/types";
import { createSlice, PayloadAction } from "@reduxjs/toolkit";

const initialState: IUserInfo = {
  status: false,
  _id: "",
  firstName: "",
  lastName: "",
  fullName: "",
  username: "",
  password: "",
  email: "",
  authenticationMethod: "",
  profileImageUrl: null,
  gender: null,
  birthDate: null,
  country: null,
  phone: null,
  address: null,
  role: "",
  expertise: [],
  courses: [],
  enrolledCourses: [],
  biography: null,
  education: [],
  experience: [],
  certifications: [],
  socialLinks: {
    linkedin: "",
    twitter: "",
    website: "",
  },
  createdAt: null,
  updatedAt: null,
};

const userInfoSlice = createSlice({
  name: "userInfo",
  initialState,
  reducers: {
    // Reducer to update user information
    updateUserInfo: (state, action: PayloadAction<Partial<IUserInfo>>) => {
      return { ...state, ...action.payload, status: true }; // Update state with new info and set status to true
    },
    // Reducer to reset user information to initial state
    resetUserInfo: () => initialState,
  },
});

// Exporting actions generated by the slice
export const { updateUserInfo, resetUserInfo } = userInfoSlice.actions;
// Exporting the reducer function for the slice
export default userInfoSlice.reducer;
